### ISSUE TITLE
Completion for bitflags!()-generated structs is broken (again?)

### ISSUE THREAD

**Issue by aldanor** [intellij-rust/intellij-rust#10019]
## Environment

* **IntelliJ Rust plugin version:** 0.4.186.5143-223
* **Rust toolchain version:** 1.66.1
* **IDE name and version:** CLion 2022.3.1
* **Operating system:** macOS Ventura

## Problem description

- `bitflags` is a pretty popular crate (in top 30 by downloads) but it seems like completion is broken as generated struct methods and associated constants can not be detected.
- Interestingly enough, if you place this macro within a function, then it works (see example in the screenshot below). Could it be some weird problem with visibility?
- 'Recursive expansion' from context menu also seems to be working correctly.
- An old closed ticket but may be relevant: https://github.com/intellij-rust/intellij-rust/issues/3611. Not sure if there was ever a time where bitflags structs were properly treated – i.e. is it still broken or was it never working.

![image](https://user-images.githubusercontent.com/2418513/213877003-62494d94-8a83-495a-83a7-7e11e73e7f3c.png)

**Comment by aldanor** [comment]
Using the previous version (bitflags 1.3.2) – constants can be found but highlighting of the constants is wrong (looks related to #8649). This doesn't cancel the question why it doesn't work with v2.0 though...

![image](https://user-images.githubusercontent.com/2418513/213880759-aa62f173-7f13-428b-bb73-e16dbdb34924.png)

**Comment by mxk** [comment]
[bitflags v2](https://docs.rs/bitflags/latest/bitflags/) is now the current release and completion is still broken with plugin v0.4.191.5293-223.

**Comment by maltaisn** [comment]
Seems mostly fixed with bitflags v2.1.0. There's still the "`Self` doesn't implement `LowerHex` (required by {:#x})" warning though.
![image](https://user-images.githubusercontent.com/33690959/232324644-70792dd8-912a-4333-85fa-3b21209cc8ee.png)

**Comment by mxk** [comment]
No, there is still no method completion with v2.1.0, CLion 2023.1.1, and plugin v0.4.192.5324-231.

**Comment by NixyJuppie** [comment]
Can confirm false-positive error 
```
 `Self` doesn't implement `LowerHex` (required by {:#x}) [E0277]
```

IDE: Rider 2023.2 EAP9
Rust plugin:  0.4.198.5409-232
Rust: 1.70.0
bitflags: 2.3.3

**Comment by Antikyth** [comment]
Can confirm this is still an issue using RustRover.

**Comment by lylythechosenone** [comment]
Yeah, I still see this issue (rustc nightly 1.77). Hopefully this gets some attention soon, because it's a big one.

**Comment by kaphula** [comment]
Please fix. Thanks!
