### ISSUE TITLE
Question: Cannot find declaration to go to error for external libs

### ISSUE THREAD

**Issue by amanjeev** [intellij-rust/intellij-rust#2238]
Thank you for taking time to look at this. This is **not** urgent.

# Brief description
When I try to "jump-to-declaration" command in IntelliJ IDEA, I get an error `cannot find declaration to go to` for core lib (see screenshot below). This works when I try to go to a local source/mod like `test`.

# Result
## For core lib
Error: Cannot find declaration to go to
![screen shot 2018-01-29 at 7 39 01 am](https://user-images.githubusercontent.com/160476/35510902-f9174e18-04c7-11e8-8877-270ffc796b90.png)

## For project files
Works as expected --> Opens the corresponding source file in a new tab.

# Details
- IntelliJ : `2017.3.3`
- Rust plugin : `0.2.0.2085`
- OS: `MacOS Sierra 10.12.6`
- Other IDE tried : CLion (same error)

# Plugin settings
![screen shot 2018-01-29 at 7 45 57 am](https://user-images.githubusercontent.com/160476/35511042-7fb442e6-04c8-11e8-8561-4184b3229208.png)

# `rustup` component details
```
$ rustup component add rust-src
info: component 'rust-src' is up to date

$ which rustup
/Users/AJ/.cargo/bin/rustup

$ which cargo
/Users/AJ/.cargo/bin/cargo

$ rustup toolchain list
stable-x86_64-apple-darwin
nightly-x86_64-apple-darwin (default)
```

**Comment by vlad20012** [comment]
I've reproduced it on Linux. I don't completely understand what's went wrong, but everything was fixed by re-opening the project.

**Comment by amanjeev** [comment]
@vlad20012 oddly it did start working after reopening project or restarting the IDE. This issue is pretty sporadic and shows up occasionally. I guess we can close this for now.

**Comment by edmondja** [comment]
Awesome, it solved it for me as well (unlike those solutions --' https://stackoverflow.com/questions/37282285/intellij-cannot-find-any-declarations), thank you guys !

**Comment by alonsoir** [comment]
I have the same problem but the solution provided is not working to me.

`IntelliJ IDEA 2019.1 (Community Edition)
Build #IC-191.6183.87, built on March 27, 2019
JRE: 1.8.0_202-release-1483-b39 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.4`

Please help!

**Comment by Patrik-Stas** [comment]
This started happening quite suddenly in all of my Rust projects (not sure, but maybe after after upgrading from Rust 1.34 to 1.36). Solved by `File -> Invalidate Caches / Restart`, then select `Invalidate and restart`. Note that on next startup it will take some time to reindex files.

**Comment by webern** [comment]
I'm new to the Rust ecosystem but have just discovered that I have this issue with Clion:
```
CLion 2019.2.3
Build #CL-192.6817.18, built on September 24, 2019
Licensed to Amazon Corporate, LLC / Matt Briggs
Subscription is active until May 1, 2020
Runtime version: 11.0.4+10-b304.69 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6
GC: ParNew, ConcurrentMarkSweep
Memory: 1987M
Cores: 12
Registry: run.processes.with.pty=TRUE, cidr.max.intellisense.file.length=5000000
Non-Bundled Plugins: com.arcticicestudio.nord.jetbrains, com.dubreuia, com.markskelton.one-dark-theme, com.thvardhan.gradianto, org.toml.lang, org.rust.lang
```

And Intellij-Rust
![image](https://user-images.githubusercontent.com/6260372/68078346-76661e80-fd91-11e9-8f19-a8bb68c5e5d1.png)

**Comment by webern** [comment]
> @vlad20012 oddly it did start working after reopening project or restarting the IDE. This issue is pretty sporadic and shows up occasionally. I guess we can close this for now.

Doesn't seem like this should be closed.

**Comment by maxpiepenbrink** [comment]
This is happening to me! And is also not urgent, but could use improvement.

```
IntelliJ IDEA 2019.3.1 (Community Edition)
Build #IC-193.5662.53, built on December 17, 2019
Runtime version: 11.0.5+10-b520.17 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: 
Non-Bundled Plugins: org.toml.lang, org.rust.lang
```

![image](https://user-images.githubusercontent.com/240875/71381755-c7241780-2589-11ea-8c47-deb205f45884.png)

```stable-x86_64-pc-windows-msvc unchanged - rustc 1.40.0 (73528e339 2019-12-16)```

I was following along with some of the examples in Tokio: https://github.com/tokio-rs/tokio/blob/master/examples/echo-udp.rs and hit this blip in the user experience with this Rust IntelliJ plugin. 

The symptom is basically this:

![image](https://user-images.githubusercontent.com/240875/71381871-4d405e00-258a-11ea-8227-36ede300c930.png)

In this case, the plugin is struggling to understand that the `tokio::net::` module has this declaration (and more) within it, however it works just fine when I do a `cargo check` or `cargo run`.

Things I've tried:

* Restarting IntelliJ
* "Refresh Cargo project"
* IntelliJ's "invalidate caches & restart" command
* Deleting the `.idea/` files in the hierarchy of my project

This is effectively a dead-simple "hello world" project with a toml that has this as the Cargo.toml:

```
[package]
name = "hello-world"
version = "0.1.0"
authors = blah
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2", features = ["full"] }
```

Any help is appreciated.

**Comment by avinash8083** [comment]
I am getting this error in my java project ,did everything ,didn't solve my problem ,i am fed up with this

**Comment by arkanmgerges** [comment]
I had this problem with Intellij Community, and now the issue is resolved with Rust plugin version 0.4.166.4486-213

![image](https://user-images.githubusercontent.com/7836805/159766475-8ffd9abf-0783-46ae-ad53-5f137c14cbe2.png)
