### ISSUE TITLE
Debugger not working on macOS

### ISSUE THREAD

**Issue by syjiangrui** [intellij-rust/intellij-rust#2751]
## Environment

* **Intellij-Rust plugin version:** 0.2.0.2103-182
* **Rust toolchain version:** 1.28.0 (9634041f0 2018-07-30)
* **IDE name and version:** CLion 2018.2
Build #CL-182.3684.76, built on July 20, 2018 . Xcode 9.4.1 lldb-902.0.79.7 
* **Operating system:** macOS 10.13.6

## Problem description

Debug operation do nothing but run program normally and breakpoint doesn't stop. There is no error alert show.

## Steps to reproduce

Just create a new project and add some code the debugger doesn't work.

**Comment by ortem** [comment]
@syjiangrui Could you please check if your breakpoints are not muted?

**Comment by syjiangrui** [comment]
@ortem Breakpoints with default settings.
I found the debugger works well on my another iMac with the same CLion and Xcode version.
The issue is happened on my hackintosh machine,  I don't know if it has a relationship.

**Comment by syjiangrui** [comment]
@ortem If the CLion provides more logs, we might be able to find the reason.

**Comment by ortem** [comment]
@syjiangrui You can open `Debug log settings` (by `cmd+shift+A`) and add the following line: `#com.jetbrains.cidr.execution.debugger`. After doing that, you can debug your program and then run `Compress Logs and Show in Finder` (by `cmd+shift+A`). Your log will be in `idea.log` inside zip archive.

**Comment by srgg** [comment]
@ortem In my case breakpoints execution stops on a 1st breakpoint and then on the 2nd one it is failed  with the following error:
```
Assertion failed: (Prior->Kind == MemberInfo::Field && !Prior->FD && "Only storage fields have tail padding!"), function clipTailPadding, file /opt/buildAgent/work/88b0b38de3dd1acc/lldb/llvm/tools/clang/lib/CodeGen/CGRecordLayoutBuilder.cpp, line 590.

```

I'd tried to do cmd+shift+A && #com.jetbrains.cidr.execution.debugger ,unfortunately I've got  "no matches found".


CLion 2018.2.2
rustc 1.28.0 (9634041f0 2018-07-30)
Intellij-Rust plugin version 0.2.0.2104-182
lldb-1000.0.18.3
xcode-select version 2349
macOs 10.13.6 (17G65)

**Comment by srgg** [comment]
@ortem Thank you, I've got archive, but from the cursory glance I haven't found anything interesting:

```
2018-08-28 13:45:34,792 [ 911428]  DEBUG - brains.cidr.execution.debugger - LLDBFrontend: Assertion failed: (Prior->Kind == MemberInfo::Field && !Prior->FD && "Only storage fields have tail padding!"), function clipTailPadding, file /opt/buildAgent/work/88b0b38de3dd1acc/lldb/llvm/tools/clang/lib/CodeGen/CGRecordLayoutBuilder.cpp, line 590.
 ```

What do you want me to do with this archieve?

**Comment by ortem** [comment]
@srgg Could you please attach the source code to reproduce this bug?

**Comment by srgg** [comment]
@ortem thank you for your help.

I terribly sorry, but I can't realize how to reproduce this in foobar,. Therefore  you'll need to clone this branch https://github.com/srgg/exonum/tree/improve-atrix-web-integration

Import the entire project into Clion and use the following cargo comand:
```test -p exonum --lib api::check_middleware_creation```

The breakpoint should be set  at the _exonum/src/api/backends/actix.rs:144_

When execution will stop on it please add variable named 'holder' in the Variable toll window , this will trigger the issue.

BTW, somehow I've got a bit exrended error this time:

```
error: need to add support for DW_TAG_base_type '()' encoded with DW_ATE = 0x7, bit_size = 0
Assertion failed: (Prior->Kind == MemberInfo::Field && !Prior->FD && "Only storage fields have tail padding!"), function clipTailPadding, file /opt/buildAgent/work/88b0b38de3dd1acc/lldb/llvm/tools/clang/lib/CodeGen/CGRecordLayoutBuilder.cpp, line 590.
```

**Comment by marvinguo** [comment]
mac, I used CLion with bundled lldb to debug c/c++ program. I can not debug(set a breakpoint not working). If I changed the debugger from bundled lldb to rust-lldb, it had an error "lldb: unrecognized option `-interpreter=mi2'". Also , rustup does not ship a gnu version rust.

Everything works fine in my ubuntu environment. Same rust& CLion.

**Comment by ortem** [comment]
@marvinguo could you please check your problem on the lastest CLion & IJ Rust plugin versions? I've fixed some problems related to debugging and breakpoints recently, so maybe it helps.

**Comment by ortem** [comment]
@srgg does the problem still exist? Does it affect other Rust code? If so, have you tried to debug the code via console lldb? Probably the problem is due to lldb (or rustc), but not CLion itself.

**Comment by marvinguo** [comment]
@ortem It can work now, thank you.

**Comment by canufeel** [comment]
This error `error: need to add support for DW_TAG_base_type '()' encoded with DW_ATE = 0x7, bit_size = 0` is still present though you can still debug things after it shows up. Switching to `rust-lldb` changes the error to:
```
warning: ignoring unknown option: --one-line-before-file=command script import "/Users/some/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/etc/lldb_rust_formatters.py"
warning: ignoring unknown option: --one-line-before-file=type summary add --no-value --python-function lldb_rust_formatters.print_val -x ".*" --category Rust
warning: ignoring unknown option: --one-line-before-file=type category enable Rust
warning: ignoring unknown option: -interpreter=mi2
Evaluation hung: python sys.path.insert(0, "/Users/some/Library/Application Support/CLion2019.1/intellij-rust/prettyPrinters"); import gdb_lookup; gdb_lookup.register_printers(gdb); 
 This may be caused by something like a deadlock or an infinite loop.
 To prevent this from happening when variables are calculated, please toggle 'Enable value renderers' off.

Process finished with exit code 0

```

**Comment by meganwoods** [comment]
I have no debug function on OSX using CLion for rust. 
I can use rust-lldb from the command line successfully debug but in CLion it does not stop for breakpoints.

IntelliJ Rust plugin: 0.2.102.2130-192
Operating System: macOS Mojave 10.14.6 (18G87)


```
2019-08-09 08:20:21,007 [39647436]   INFO - lij.diagnostic.DebugLogManager - Set DEBUG for the following categories: #com.jetbrains.cidr.execution.debugger 
2019-08-09 08:20:21,367 [39647796]   INFO - rationStore.ComponentStoreImpl - Saving Project '/Users/meganwoods/rust/foo' fooChangeListManager took 17 ms 
2019-08-09 08:20:28,023 [39654452]   WARN - j.openapi.wm.impl.IdeFrameImpl - Set preferredFocusableComponent in 'Output' content in Run tool window to avoid focus-related problems. 
2019-08-09 08:20:28,024 [39654453]   WARN - j.openapi.wm.impl.IdeFrameImpl - Output tool window - parent container is hidden 
2019-08-09 08:20:28,156 [39654585]  DEBUG - brains.cidr.execution.debugger - LLDBFrontend: /Applications/CLion.app/Contents/bin/lldb/mac/LLDBFrontend 59051
 
2019-08-09 08:20:28,161 [39654590]   WARN - j.openapi.wm.impl.IdeFrameImpl - Set preferredFocusableComponent in 'run' content in Debug tool window to avoid focus-related problems. 
2019-08-09 08:20:28,161 [39654590]   WARN - j.openapi.wm.impl.IdeFrameImpl - run tool window - parent container is hidden 
2019-08-09 08:20:28,366 [39654795]  DEBUG - brains.cidr.execution.debugger - [protobuf client 7] 236 res:composite_broadcast {
  initialized {
    version_string: "7.0.1"
    version_string_original: "lldb version 7.0.1"
  }
} 
2019-08-09 08:20:28,366 [39654795]  DEBUG - brains.cidr.execution.debugger - [protobuf client 7] 237 req(87): handle_console_command {
  thread_id: 4294967295
  frame_index: -1
  command: "settings set target.process.thread.step-in-avoid-nodebug true"
} 
2019-08-09 08:20:28,367 [39654796]  DEBUG - brains.cidr.execution.debugger - [protobuf client 7] 238 req(88): handle_console_command {
  thread_id: 4294967295
  frame_index: -1
  command: "settings set target.process.thread.step-out-avoid-nodebug true"
} 
2019-08-09 08:20:28,367 [39654796]  DEBUG - brains.cidr.execution.debugger - [protobuf client 7] 238 req(136): handle_console_command {
  thread_id: 4294967295
  frame_index: -1
  command: "type summary add --skip-pointers --summary-string \"${var%d} ${var}\" --category cplusplus \"char\" \"signed char\""
} 
2019-08-09 08:20:28,368 [39654797]  DEBUG - brains.cidr.execution.debugger - [protobuf client 7] 238 req(130): handle_console_command {
  thread_id: 4294967295
  frame_index: -1
  command: "type summary add --skip-pointers --summary-string \"${var%u} ${var}\" --category cplusplus \"unsigned char\""
} 
2019-08-09 08:20:28,368 [39654797]  DEBUG - brains.cidr.execution.debugger - [protobuf client 7] 239 req(51): handle_console_command {
  thread_id: 4294967295
  frame_index: -1
  command: "type category enable objc"
} 
2019-08-09 08:20:28,368 [39654797]  DEBUG - brains.cidr.execution.debugger - [protobuf client 7] 239 req(9): values_filtering_policy {
  filter_enabled: 1
} 
2019-08-09 08:20:28,368 [39654797]  DEBUG - brains.cidr.execution.debugger - [protobuf client 7] 239 res:handle_console_command {
  common_response {
    is_valid: true
  }
  success: 1
} 
2019-08-09 08:20:28,368 [39654797]  DEBUG - brains.cidr.execution.debugger - [protobuf client 7] 239 res:handle_console_command {
  common_response {
    is_valid: true
  }
  success: 1
} 
2019-08-09 08:20:28,369 [39654798]  DEBUG - brains.cidr.execution.debugger - [protobuf client 7] 239 req(80): handle_console_command {
  thread_id: 4294967295
  frame_index: -1
  command: "script import lldb_formatters.jetbrains_stl_formatters"
} 
2019-08-09 08:20:28,369 [39654798]  DEBUG - brains.cidr.execution.debugger - [protobuf client 7] 240 res:handle_console_command {
  common_response {
    is_valid: true
  }
  success: 1
} 
2019-08-09 08:20:28,369 [39654798]  DEBUG - brains.cidr.execution.debugger - [protobuf client 7] 240 res:handle_console_command {
  common_response {
    is_valid: true
  }
  success: 1
} 
2019-08-09 08:20:28,369 [39654798]  DEBUG - brains.cidr.execution.debugger - [protobuf client 7] 240 res:handle_console_command {
  common_response {
    is_valid: true
  }
  success: 1
  err: "warning: empty category enabled (typo?)\n"
} 
2019-08-09 08:20:28,369 [39654798]  DEBUG - brains.cidr.execution.debugger - [protobuf client 7] 240 res:values_filtering_policy {
  common_response {
    is_valid: true
  }
} 
2019-08-09 08:20:28,374 [39654803]  DEBUG - brains.cidr.execution.debugger - [protobuf client 7] 240 req(153): handle_console_command {
  thread_id: 4294967295
  frame_index: -1
  command: "command script import \"/Users/meganwoods/Library/Application Support/CLion2019.2/intellij-rust/prettyPrinters/lldb_lookup.py\" "
} 
2019-08-09 08:20:31,595 [39658024]   WARN - brains.cidr.execution.debugger - Cannot detach/abort. Forcing driver termination 
```

Let me know if you need any more information.

**Comment by ortem** [comment]
@meganwoods 
1. Is there any message inside LLDB console? The console is located inside Debug tab.
2. Could you please provide the source code which you're trying to debug?

**Comment by ortem** [comment]
@canufeel Did you try using `rust-lldb` inside CLion? CLion doesn't support custom lldb, so you cannot use `rust-lldb`. On macOS, you should choose `Bundled LLDB` inside `Preferences | Build, Execution, Deployment | Toolchains` settings.

**Comment by meganwoods** [comment]
Hi, @ortem

There is no output in the LLDB tab of the Debugger pane.

Interestingly there is no output other than "Process finished with exit code 0" in the applications console output when running via debug. 

The expected output is there when the application is invoked via "run".

Example project:
[foo.zip](https://github.com/intellij-rust/intellij-rust/files/3490085/foo.zip)

Let me know if you need anything else.

**Comment by ortem** [comment]
@meganwoods Thank you for providing the information! Looks like this issue relates to CLion itself, not the IntelliJ Rust plugin, so I've passed the information to CLion team. There is a similar known issue with CLion 2019.2 on macOS 10.15.

However, you should try to reinstall CLion and restart your computer. Please let me know whether it solves your problem.

**Comment by meganwoods** [comment]
Hi @ortem 

I reinstalled CLion and debugging works as expected now.

Thanks for your help.

Megan

**Comment by fryziuk** [comment]
Hi, I have same Issue. Mac OS Mojave 10.14.6 Clion 2019.2.3 When I use libfuzzer from llvm. Strange that lldb from console works well. And when I debug code without libfuzzer and address sanitizers. Debugger works ok in CLion and console. I use bundled lldb 7.0.1

**Comment by windev92** [comment]
installed today Clion from scratch and rust plugin, using default settings (lldb). osx catalina 10.15 Beta. it doesn't debug at all. lldb tab is empty and variables tab shows "connecting". debugger is still running and need to stop it manually. my programs is supposed to print out stuff but cannot see anything in the console. i think the app doesn't even start. what shall i do ?

**Comment by windev92** [comment]
> @syjiangrui You can open `Debug log settings` (by `cmd+shift+A`) and add the following line: `#com.jetbrains.cidr.execution.debugger`

After having done that, I have a yellow terminal window if I do cmd+shift+A again. and it displays :
No manual entry for debug log\;type\=a

[Process completed]

**Comment by Undin** [comment]
@windev92 it's another problem related to macOS 10.15
Try to update to CLion 2019.2.4. See https://blog.jetbrains.com/clion/2019/10/clion-2019-2-4-bug-fix-update/ for more details

**Comment by ortem** [comment]
Looks like all issues have been fixed on CLion side so this can be closed
