### ISSUE TITLE
IDE hangs every few minutes

### ISSUE THREAD

**Issue by gavofyork** [intellij-rust/intellij-rust#4131]
## Environment

* 0.2.101.2129-191
* 1.36.0
* IntelliJ IDEA community 2019.1
* MacOS 10.14.5

## Problem description

The IDE hangs (spinning beachball) every few minutes for 5-20 seconds. I've tried increasing available heap memory (it's currently at 768MB, but I've had it as high as 4GB). There is no discernible difference. I've tried entering power save mode, also no obvious difference.

## Steps to reproduce

I'm working on Parity Substrate, which is a fairly large and very generic-heavy project. Presumably this is just the Java GC horribleness kicking in and stalling everything; on the occasions I've checked the CPU, IntelliJ  seems limited to a single thread. In any case, if you load the project and start editing code it should happen sooner or later.

~Most recently I've had it hang longer than the usual 10 seconds or so - I attach the sample of that.~ (The indefinite hanging is now fixed)

**Comment by sirgl** [comment]
I had some problems earlier either, but for me works the following: enable low pause concurrent GC shenandoah and set heap size 1,5GB, after that I've never seen any noticeable pauses.

It is workaround, but still.

**Comment by gavofyork** [comment]
Do you have any pointers on how to enable that?

**Comment by sirgl** [comment]
1. Install jdk with shenondoah: https://developers.redhat.com/products/openjdk/overview?utm_source=jdkdev&utm_medium=download
2. Set it as intellij boot sdk: https://intellij-support.jetbrains.com/hc/en-us/articles/206544879-Selecting-the-JDK-version-the-IDE-will-run-under
3. Setting -> Edit custom VM options -> add -Xmx1500m and -XX:+UseShenandoahGC
4. Restart

**Comment by gavofyork** [comment]
I'll give it a go! Cheers :)

**Comment by gavofyork** [comment]
Got it installed and tested, but it seems IntelliJ doesn't work with it.

**Comment by sirgl** [comment]
Sorry, forget to mention that intellij works only with 8 or 11 jdk.

**Comment by gavofyork** [comment]
Ahh :)

**Comment by gavofyork** [comment]
Tried v11; now I get the splash screen and the progress bar gets to the right side, but then it just hangs :( So close...

**Comment by gavofyork** [comment]
Here's another sample of an indefinite hang.
[Sample of IntelliJ IDEA.txt](https://github.com/intellij-rust/intellij-rust/files/3381952/Sample.of.IntelliJ.IDEA.txt)

**Comment by ortem** [comment]
Hi @gavofyork, could you please provide the log and thread dumps? You can do it [this way](https://github.com/intellij-rust/intellij-rust/issues/4087#issuecomment-507588710).

**Comment by gavofyork** [comment]
[threadDumps-freeze-20190711-142059-IC-191.7479.19.zip](https://github.com/intellij-rust/intellij-rust/files/3381978/threadDumps-freeze-20190711-142059-IC-191.7479.19.zip)
[idea.log](https://github.com/intellij-rust/intellij-rust/files/3381980/idea.log)

**Comment by mchernyavsky** [comment]
@gavofyork Please, check the latest nightly build. I think your issue is already fixed -- https://github.com/intellij-rust/intellij-rust/pull/4114.

**Comment by gavofyork** [comment]
Ok - should I open a separate issue for the temporary 5-20 second hanging?

**Comment by ortem** [comment]
@gavofyork No, just check the nightly build and tell us if the problem still exists.

**Comment by gavofyork** [comment]
I can confirm that the occasional temporary hangs still occur with nightly.

**Comment by ortem** [comment]
@gavofyork could you please provide us your logs once again? But now via `Compress logs and show...` action, because it provides more information about multiple freezes. Thanks in advance!

**Comment by philipr-za** [comment]
I have been having a similar issue while working in a Rust project in IntelliJ. Every 10 minutes to and hour the IDE fully hangs and never recovers. As suggested in this Issue I have installed the Nightly release but it still happens. Support suggested I add my logs to this issue.
[threadDumps-freeze-20190719-111535-IU-192.5728.74.zip](https://github.com/intellij-rust/intellij-rust/files/3410396/threadDumps-freeze-20190719-111535-IU-192.5728.74.zip)
[idea.log](https://github.com/intellij-rust/intellij-rust/files/3410397/idea.log)

**Comment by vlad20012** [comment]
@philipr-za 
I tried to fix the same issue in #4114.
Could you please try the latest nightly _IntelliJ Rust plugin_ (see [instructions](https://intellij-rust.github.io/install.html))?

**Comment by philipr-za** [comment]
Thanks, a couple days in and still looks good.

**Comment by neonaot** [comment]
It looks like this bug has already been fixed!
Please reopen if the problem persists.
