### ISSUE TITLE
main.rs is not interpreted as runnable/debuggable file.

### ISSUE THREAD

**Issue by TimonPost** [intellij-rust/intellij-rust#5739]
## Environment

* **IntelliJ Rust plugin version: 0.2.123.3132-193**
* **Rust toolchain version:  rustup 1.22.1 (b01adbbc3 2020-07-08)**
* **IDE name and version: CLION**

```
CLion 2019.3.5
Build #CL-193.6911.21, built on March 17, 2020
Linux 4.19.0-9-amd64
```

* **Operating system:**
Linux

## Problem description

- The run/debug button is not shown in the tooltip navigation menu when clicking the right mouse button  on `main.rs`
- The file `main.rs` has no syntax highlighting. 

**How it should work**
![image](https://user-images.githubusercontent.com/19969910/87425284-aa126d00-c5dd-11ea-81fd-bcaa3e818777.png)

**How it works**
![image](https://user-images.githubusercontent.com/19969910/87425219-851dfa00-c5dd-11ea-8eed-5a1425a3d6fe.png)

The following buttons still work:

![image](https://user-images.githubusercontent.com/19969910/87424758-cf52ab80-c5dc-11ea-8f26-9b723d2e2acc.png)

Also, all the creates in this project are referred and listed in the `cargo list`.

![image](https://user-images.githubusercontent.com/19969910/87424972-34a69c80-c5dd-11ea-96f5-22d6230300e8.png)

## Steps to reproduce

None, this happens randomly.

## My solution

- Copy code from `main.rs`
- Remove `main.rs`
- Recreate `main.rs` this will fix the bug, but it can happen again.

**Comment by vlad20012** [comment]
Looks very weird, but before we'll try to think fo something, could you please update CLion to `2020.1`? You use old `2019.3.5` version of CLion and hence old `0.2.123` version of IntelliJ Rust (we don't release new versions for old 2019.3 IDEs), and then try to reproduce it again. It's possible that the bug is fixed already in the modern plugin

**Comment by vlad20012** [comment]
Hmm, also check that you don't have `Oxidize` plugin installed

**Comment by TimonPost** [comment]
I'm now using rust plugin `0.3.126.3220-201` and clion ` 2020.1.2` now. The issue remains. 

It's interesting that with the new updates I get to see this icon.

![image](https://user-images.githubusercontent.com/19969910/87791033-dc240900-c841-11ea-8345-e47d100574a7.png)

**Comment by Undin** [comment]
@TimonPost your `main.rs` file is marked as plain text file. Try to invoke `Mark as Rust Files` from context menu

**Comment by Undin** [comment]
BTW this action is even shown on your PR in issue
![87425219-851dfa00-c5dd-11ea-8eed-5a1425a3d6fe](https://user-images.githubusercontent.com/2539310/87792978-4bebc100-c84d-11ea-86e8-dc7f64132e34.png)

**Comment by TimonPost** [comment]
I actually saw that option while trying to fix it today, but did not work. I recreated the files, I will see if after recreating the problems are resolved. So I keep this issue up to date on new information.

**Comment by TimonPost** [comment]
They went corrupted again, however, marking the files as 'rust' files worked now. After checking that I haven't seen any problems anymore. I will close this issue for now. Thanks for the suggestions!
