### ISSUE TITLE
Allow Code Completeion on Detached Files

### ISSUE THREAD

**Issue by reesmanp** [intellij-rust/intellij-rust#6926]
## Environment

* **IntelliJ Rust plugin version:** 0.3.142.3705-203
* **Rust toolchain version:** 1.45.0
* **IDE name and version:** CLion 2020.3.2
* **Operating system:** Windows 10

## Problem description
Due to the large amount of files I have in a directory, having to export them, and having an enum variant that maps to each file, I want to keep the code amount lower to provide for easier maintenance. I have built a macro that `mod`'s, `pub use`'s, and builds an enum with each as a variant. These files are now seen as detached and now code completion is off.

## Steps to reproduce

main.rs
- modA
  - modC
- modB
  - modD

modB just propagates the macros to main which exposes it to the rest of the crate via `#[macro_use]`.

```rust
// modD
macro_rules! use_mod_impl_enum {
    [$enum_name:ident $(, $enum_variant:ident($mod:ident::$function:ident) $(,)?)*] => {
        // Gives pub visibility with easier to use name
        pub use {
            $($mod::$function,)*
        };
        // Adds item to Rust tree
        $(mod $mod;)*
        // Create enum Function
        pub enum $enum_name {
            // For each variant, create it
            $($enum_variant($function),)*
        }
        // Implements enum Function
        impl $enum_name {
            pub fn calculate(&self, arguments: &Vec<String>) -> Result<(), Error> {
                match self {
                    // For each variant of the enum, create a match arm and call calculate on it
                    $(Self::$enum_variant(item) => item.calculate(&arguments),)*
                }
            }
        }
    }
}
```

```rust
// modA
use_mod_impl_enum![
    MyEnum,
    VARIANT_1(modC::Struct_1)
];
```

```rust
// modC
use std::fmt::Error;

pub struct Struct_1;

impl Struct_1 {
    pub fn test(&self) ->Result<(), Error> {
        // Code completion stops
        Ok(String::new())
    }
}
```

**Comment by Undin** [comment]
@reesmanp thanks for the report!

Are you sure that `use_mod_impl_enum` macro is imported properly and your code can be compiled? If yes, could you provide the exact code of your modules, please? If `use_mod_impl_enum` is properly imported, `modC`  should be attached to the project from the plugin's point of view. If it's not so, it's a bug and it should be fixed instead of allowing "Code Completeion on Detached Files"

**Comment by reesmanp** [comment]
@Undin the code is basically the same as I pasted here. The only file I didn't add was modB which is literally
```rust
#[macro_use]

pub mod macros;
```

I can confirm that it compiles and runs correctly.

**Comment by vlad20012** [comment]
I can't reproduce. The minimal setup described in this issue works as expected and doesn't lead to detached modules

**Comment by reesmanp** [comment]
Interesting, especially since I upgraded to latest yesterday and it is still happening for me.

- main.rs
  - util/
    - mod.rs
    - macro.rs
  - formulas/
    - mod.rs
    - functions/
      - mod.rs
      - avg.rs
 
In main.rs we have this at the top:
```rust
// Util comes first to export macros
#[macro_use]
mod util;

mod formulas;
```

util/mod.rs is literally just
```rust
#[macro_use]
pub mod macros;
```

util/macros.rs is entirely (I modularized it a bit since original post):
```rust
/// Adds functions to Rust tree and gives visibility
/// Creates an enum and implements the calculate function on it
/// Much easier to add variants now since we have so many functions
/// usage:
/// use_mod_impl_enum![<ENUM_NAME>, <ENUM_VARIANT_1>(<FILE_MOD_1>::<FUNCTION_STRUCT_NAME_1>), ...];
/// example:
/// use_mod_impl_enum![Function, ABS(abs::FunctionABS), AND(and::FunctionAND)];
macro_rules! use_mod_impl_enum {
    [$enum_name:ident $(, $enum_variant:ident($mod:ident::$function:ident) $(,)?)*] => {
        // Gives pub visibility with easier to use name
        pub use {
            $($mod::$function,)*
        };
        // Adds item to Rust tree
        $(mod $mod;)*
        // Create enum Function
        pub enum $enum_name {
            // For each variant, create it
            $($enum_variant($function),)*
        }
        impl_enum![$enum_name $($enum_variant,)*];
    }
}

/// Creates an enum and implements the calculate function on it
/// usage:
/// use_mod_impl_enum![<ENUM_NAME>, <ENUM_VARIANT_1>(<FILE_MOD_1>::<FUNCTION_STRUCT_NAME_1>), ...];
/// example:
/// use_mod_impl_enum![FormulaNodeType, FUNCTION(functions::Function), LITERAL(literals::Operator)];
macro_rules! impl_formula_enum {
    [$enum_name:ident $(, $enum_variant:ident($mod:ident::$function:ident) $(,)?)*] => {
        use crate::formulas::{$($mod::$function,)*};
        // Create enum Function
        pub enum $enum_name {
            // For each variant, create it
            $($enum_variant($function),)*
        }
        impl_enum![$enum_name $($enum_variant,)*];
    }
}

/// Creates the impl of an enum for the calculate api contract
/// Used internally
macro_rules! impl_enum {
    [$enum_name:ident $($enum_variant:ident,)*] => {
        // Implements enum Function
        impl $enum_name {
            pub fn calculate(&self, arguments: &Vec<FormulaNode>) -> Result<FormulaOutput, Error> {
                match self {
                    // For each variant of the enum, create a match arm and call calculate on it
                    $(Self::$enum_variant(item) => item.calculate(&arguments),)*
                }
            }
        }
    }
}
```

formulas/mod.rs contains:
```rust
pub mod functions;
```

The entirety of formulas/functions/mod.rs is:
```rust
use crate::formulas::{
    FormulaNode,
    FormulaOutput
};
use std::fmt::Error;

use_mod_impl_enum![
    Function,
    AVG(avg::FunctionAVG)
];
```

Lastly the formulas/functions/avg.rs is:
```rust
use crate::formulas::{
    FormulaNode,
    FormulaOutput,
    functions::Function
};
use std::fmt::Error;

pub struct FunctionAVG;

impl FunctionAVG {
    pub fn calculate(&self, arguments: &Vec<FormulaNode>) -> Result<FormulaOutput, Error> {
    }
}
```

This last file does not have code completion and is marked as a detached file via the warning:
"File is not included in module tree, analysis is not available"

Finally, yes, moments ago I compiled and ran this code as is successfully again.

**Comment by vlad20012** [comment]
I just repeated your setup and I can confirm that I can't reproduce the issue: the module is correctly liked to the module tree and everything works as expected:
https://user-images.githubusercontent.com/3221931/115150134-c1e8b700-a06f-11eb-9197-0843978861c6.mp4

Maybe you setup is a bit more complex

Please, check that the new macro expansion engine is enabled in `File | Settings | Languages & Frameworks | Rust | Expand declarative macros` (should be enabled by default) and the macro
```rust
use_mod_impl_enum![
    Function,
    AVG(avg::FunctionAVG)
];
```
... is resolved and expanded successfully (`alt`+`enter` -> `show recursive macro expansion`).

**Comment by reesmanp** [comment]
The `expand declarative macros` was on with the new engine. I tried the method mentioned above using both the old and new engines and neither worked. When attempting to `show recursively expanded macro` an error appears saying `failed to expand the macro` above the `use_mod_impl_enum` usage. I see in your video that the items within the usage are clickable and you can navigate to the item it is referencing, but I am not experiencing that.

**Comment by cherryleafroad** [comment]
I just want to chime in here that allowing code completion for detached files DOES have a use-case.

With [Windows-rs](https://github.com/microsoft/windows-rs), bindings are generated automatically, however there is absolutely no autocompletion on it since they are generated bindings. However, once you build the project, the source becomes available in `target\debug\build\bindings-xxxxx\out\windows.rs`, after which we _could_ attach this source to the project so we could get autocompletions.
