### ISSUE TITLE
Rust LLDB error: module importing failed: No module named 'renderers'

### ISSUE THREAD

**Issue by blueglyph** [intellij-rust/intellij-rust#8851]
## Environment

* **IntelliJ Rust plugin version:** 0.4.170.4627-221
* **Rust toolchain version:** 1.60.0 (7737e0b5c 2022-04-04) x86_64-pc-windows-msvc
* **IDE name and version:** PyCharm 2022.1.1 Professional Edition (PY-221.5591.52)
* **Operating system:** Windows 10 10.0
* **Macro expansion engine:** new
* **Name resolution engine:** new

I'm using the Visual Studio 2019 build tools for the toolchain.

## Problem description

When debugging a program, I get the following in the Rust LLDB panel:

> error: module importing failed: No module named 'renderers'
>   File "temp.py", line 1, in <module>
> 
> error: 'jb_renderers_set_diagnostics_level' is not a valid command.
> error: module importing failed: No module named 'renderers'
>   File "temp.py", line 1, in <module>
> 
> error: 'jb_renderers_loaders_add' is not a valid command.
> Breakpoint 1: where = test01.exe`std::panicking::rust_panic() at panicking.rs:743, address = 0x0000000140009d60
> error: 'jb_renderers_set_global_hex' is not a valid command.

And at each command,

> error: 'jb_renderers_set_global_hex' is not a valid command.

## Steps to reproduce

- create new Rust project
- keep the default code:
```rust
fn main() {
    println!("Hello, world!");
}
```
- place a breakpoint on the `print` line
- Debug 'run' (shift-F9)
=> error in the LLDB panel

**Comment by Undin** [comment]
It's a known issue in debugging on Windows - the debugger tries to add C++ pretty-printer scripts and can't find them

But it doesn't affect debugging of Rust code

**Comment by blueglyph** [comment]
Is there a module I can install in Python to avoid that?

**Comment by Undin** [comment]
No, it should be fixed in debugger integration itself (and most probably even not in Rust plugin itself)
But what exactly does it bother you? error messages in console or something else?

**Comment by blueglyph** [comment]
Just the messages, it's distracting but not a big problem.
If there's a simple work-around, I'd be interested to know, otherwise it's fine.

**Comment by ortem** [comment]
@blueglyph I think the simplest workaround would be to disable `Enable NatVis renderers for LLDB` checkbox in `File | Settings | Build, Execution, Deployment | Debugger | Data Views | C/C++` settings. Please let us know if that solves the problem with annoying error messages.

**Comment by blueglyph** [comment]
@ortem This solves the issue, thanks a lot!

**Comment by crutchcorn** [comment]
This is still occurring for me, but the `C/C++` settings are not present for me; this is what I see:

![image](https://github.com/user-attachments/assets/73813791-b25c-4d7b-9100-a6c7f04e1322)

**Comment by terminalHub** [comment]
I'm also having this issue that has been bothering me for a long time, is there any better solution, and now this error is causing me to be unable to continue debugging the programme.

**Comment by Darkyenus** [comment]
This happens to me as well, but in Rust Rover. I don't know if it is related or not, but the debugger also does not properly show enums (it shows all variants at once). Otherwise it seems to work, it's just not very useful when I can't inspect most variables.

**Comment by blueglyph** [comment]
> This happens to me as well, but in Rust Rover. I don't know if it is related or not, but the debugger also does not properly show enums (it shows all variants at once). Otherwise it seems to work, it's just not very useful when I can't inspect most variables.

@Darkyenus, you should report that on Jetbrain's Youtrack system. As you can read at the top of the project's page, it's deprecated. The plugin is now developed internally at Jetbrain.

**Comment by avnerz** [comment]
> This is still occurring for me, but the `C/C++` settings are not present for me; this is what I see:
> 
> ![image](https://github.com/user-attachments/assets/73813791-b25c-4d7b-9100-a6c7f04e1322)

The issue in RustRover persists just as described here on latest version 2025.1.2, despite issue being marked as closed.

**Comment by amone-bit** [comment]
@artemmukhin I also meet same issue in RustRover on latest version.
